#!/bin/bash

QUIET=
if [[ "$1" = "-q" ]]; then
   QUIET="-v0"
   shift
fi

SOURCE=$1
if [[ "$SOURCE" = "" ]]; then
   echo "usage: $0 [-q] '(code goes here)'"
   exit 1
fi
shift

FILE=`mktemp`
echo $SOURCE > $FILE && cabal $QUIET run tsc -- $FILE "$@" && ./a.out
