(display ()) (newline)
(display (cons 1 ())) (newline)
(display (cons 1 (cons 2 (cons 3 ())))) (newline)
(display (cons 1 2)) (newline)
(display (cons "hello" 3)) (newline)
(display (cons "a" (cons "b" "c"))) (newline)
